target 'WLXWebViewReloader', :exclusive => true do
  pod "WLXWebViewReloader", :path => "../"
  pod "GCDWebServer"
end

target 'Tests', :exclusive => true do
  pod "WLXWebViewReloader", :path => "../"

  pod 'Kiwi'
end
