source 'https://github.com/CocoaPods/Specs.git'

target 'WLXWebViewReloader', :exclusive => true do
  pod "WLXWebViewReloader", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "WLXWebViewReloader", :path => "../"

  pod 'Kiwi'
end
